feat: Add ping with direct flag.
ipfs-shipyard/vole pull request #38
Opened 2024-04-02 22:39 UTC by MarcoPolo

A bit more verbose than I would like because go-libp2p will always allow ping to go over a relayed connection.

2024-04-02 23:41 UTC, aschmahmann approved these changes
LGTM thanks 🙏. Although, if you've got a moment to move most of the code here into the library part and add a basic Go smoke test that'd be great.

2024-04-02 23:41 UTC, aschmahmann commented on main.go
> +							// Set the activation threshold to 1 so that we learn our own address with just one connection. This lets us holepunch sooner.
This is "at all" rather than sooner right? Since there's no source of address discovery other than from the address of the one peer that's passed in.

2024-04-03 02:39 UTC, MarcoPolo commented on lib/ping.go
> +		identify.ActivationThresh = 100
Direct won't work until we merge https://github.com/ipfs-shipyard/vole/pull/39 since that sets this to 1 in init.

2024-04-03 20:20 UTC, aschmahmann requested changes
Shouldn't `--direct=true` fail if we pass a relay address (and the peer isn't on our LAN or anything)?

For example:
```
❯ ./vole libp2p ping --direct=true /ip4/45.63.90.36/udp/4001/quic-v1/p2p/12D3KooWHH1vQP4vqKNqMsBqspgdXkebpS93D3c1RihLnCdEhkqs/p2p-circuit/p2p/12D3KooWJrgkLgasGFTXAZfECX5obhQvWYSMYuYEH9xXMH2iQZ4n
Took  39.6444ms
Took  39.8416ms
Took  40.0525ms
❯ ./vole libp2p ping --direct=false /ip4/45.63.90.36/udp/4001/quic-v1/p2p/12D3KooWHH1vQP4vqKNqMsBqspgdXkebpS93D3c1RihLnCdEhkqs/p2p-circuit/p2p/12D3KooWJrgkLgasGFTXAZfECX5obhQvWYSMYuYEH9xXMH2iQZ4n
Took  177.7831ms
Took  159.954ms
Took  165.0507ms
```

2024-04-03 20:27 UTC, MarcoPolo commented
`--direct=true` will permit holepunching and then ping on a direct connection. `--direct=false` is allowed to ping on a relayed connection. Alternative names are welcome. Maybe `--allow-ping-over-relay` ?

2024-04-03 20:42 UTC, aschmahmann commented
Ok so:
- `direct=false` : Passes because ping data is small enough to be passed by the relay-v2 node without causing a problem
- `direct=true` : Does holepunching and then does the pings (and timings) over the direct connection (which is why the pings are faster)

The naming/what we do seems like it's related to what we're trying to test. Some things I could see a debugger caring about:
1. Wanting to test if we've been able to establish a direct connection to the peer (maybe we care about how long that takes in addition to the ping durations)
2. If we can establish a relayed connection at all (in the event the above fails ^)
3. What the ping duration is via a relay (since that might be relevant in debugging holepunching if the ping duration through the relay is really long)

If this is what we care about then maybe something like `--force-relay` (false for 1, true gives 2 + 3)? We'd probably default to false.

2024-04-15 21:33 UTC, aschmahmann approved these changes

2024-04-15 21:44 UTC, merged